[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install --no-root"

[deploy]
startCommand = "poetry run api_server --host 0.0.0.0 --port $PORT" # --client.showErrorDetails false
# healthcheckPath = "/"
# healthcheckTimeout = 100
# restartPolicyType = "never"
